server:
  port: 8761

spring:
  application:
    name: DISCOVERY-SERVER

# Eureka  Configuration
eureka:
  instance:
    hostname: 3.229.47.37
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
